### ISSUE TITLE
Enhance Readme and outline limitations

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/rtc-git-commit-picker#1]
The main project description (README) needs a major rewrite, to cover the following stuff:
- Add a few screenshots to give a better guidance what the plug-in intends
- outline the current limitations (100 commits, deprecated sign-in method, ...)
- move feature list to release object
- remove todos and add respective issues where necessary

**Comment by innerjoin** [comment]
@MartinBenninger

**Comment by schneigu** [comment]
See issue 2
@MartinBenninger @Innerjoin

**Comment by innerjoin** [comment]
This project has been phased out a while ago. Anyone interested in integrating RTC with GitLab or GitHub should check out the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) project, which covers all the use cases of this repo plus many more.
If you feel like this issue is still relevant with what the [RTC Git Connector](https://github.com/jazz-community/rtc-git-connector) aims to provide, feel free to open a new issue there
