### ISSUE TITLE
Wrong implementation of Personal Access Token must be replaced

### ISSUE THREAD

**Issue by schneigu** [jazz-community/rtc-git-commit-picker#2]
The current implementation of Personal Access Token is wrong and a high security risk.

It must be removed from the code and documentation urgently!

A new implementation must be found.

Currently only the username/password login is sipported and allowed to be used.

**Comment by MartinBenninger** [comment]
This has been fixed by 499928283a2ba7f49bd04703485ec7e082e66ead

Starting with v1.1.0 only authentication using personal access tokens is allowed.

The username / password login did not provide a good user experience and was additionally deprecated in the GitLab API. Therefore it was removed.
